### PR TITLE
Security Management of Firebase

### LINKED ISSUE #8: Security management of Firebase
webfront/lib/firebase.ts and client/src/firebase.ts have confidential information.
So they need to be added to .gitignore and should not be published on GitHub.
Then, docs/SETUP.md will needs to have contents about how contributors should write firebase.ts.

### PR DESCRIPTION
**Pull request by yutomoriyasu**
This is a contribution to ISSUE #8

### CODE REVIEW

**Comment by yaggytter** [comment]
@YutoMoriyasu 
Hi Yuto!
Thank you for your contribution again.

My opinion is that client/src/firebase.ts and webfront/lib/firebase.ts will be renamed to firebase.ts.sample which use for understanding. How do you think?

**Comment by yutomoriyasu** [comment]
@yaggytter 
Thanks for the review!
In that case, do contributors have to add firebase.ts by themselves?

By the way, I thought it's normal to create .env and refer to firebase confidential codes in firebase.ts

**Comment by yaggytter** [comment]
@YutoMoriyasu 
I think, One of benefit to use Firebase is that developer can copy and paste Firebase configuration from web console to our codes. So It's important that firebase.ts is still exists. What do you think?

**Comment by yutomoriyasu** [comment]
@yaggytter 
I see your point. Then, I will rename firebase.ts to firebase.ts.sample and add some instructions for developers!

**Comment by yutomoriyasu** [comment]
@yaggytter 

I added firebase.ts.sample files and edit instructions for contributors!

**Comment by yaggytter** [comment]
@YutoMoriyasu 
Thank you!

**Pull request merged**
